"""empty message

Revision ID: 303605c35fcb
Revises: bc3a618ea37d
Create Date: 2023-08-30 16:43:11.802825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303605c35fcb'
down_revision = 'bc3a618ea37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_sides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_colors', sa.String(length=120), nullable=True))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('colors')

    with op.batch_alter_table('card_sides', schema=None) as batch_op:
        batch_op.drop_column('side_colors')

    # ### end Alembic commands ###
