"""empty message

Revision ID: 36c3a30b762f
Revises: ff7ab17536bd
Create Date: 2023-07-01 12:13:49.293966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c3a30b762f'
down_revision = 'ff7ab17536bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_sides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_power', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('side_toughness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('side_loyalty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('side_defense', sa.Integer(), nullable=True))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('toughness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('defense')
        batch_op.drop_column('loyalty')
        batch_op.drop_column('toughness')
        batch_op.drop_column('power')

    with op.batch_alter_table('card_sides', schema=None) as batch_op:
        batch_op.drop_column('side_defense')
        batch_op.drop_column('side_loyalty')
        batch_op.drop_column('side_toughness')
        batch_op.drop_column('side_power')

    # ### end Alembic commands ###
