"""empty message

Revision ID: 7532fefb765d
Revises: 303605c35fcb
Create Date: 2023-09-01 11:26:04.733816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7532fefb765d'
down_revision = '303605c35fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commander', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('oathbreaker', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signature_spell', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cards_in_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_commander', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_oathbreaker', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_signature_spell', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards_in_decks', schema=None) as batch_op:
        batch_op.drop_column('is_signature_spell')
        batch_op.drop_column('is_oathbreaker')
        batch_op.drop_column('is_commander')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('signature_spell')
        batch_op.drop_column('oathbreaker')
        batch_op.drop_column('commander')

    # ### end Alembic commands ###
