"""empty message

Revision ID: 8edcb4e18dbf
Revises: cca0501ae253
Create Date: 2023-06-21 16:31:23.946716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edcb4e18dbf'
down_revision = 'cca0501ae253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('card_total')

    # ### end Alembic commands ###
