"""empty message

Revision ID: 95981b7a3273
Revises: 
Create Date: 2023-06-01 11:35:49.914068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95981b7a3273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oracle_text', sa.String(length=250), nullable=True))
        batch_op.alter_column('flavor_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('rules_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules_text', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.alter_column('flavor_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('oracle_text')

    # ### end Alembic commands ###
