"""empty message

Revision ID: bc3a618ea37d
Revises: ee5a1309c2b1
Create Date: 2023-08-29 14:23:30.102752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3a618ea37d'
down_revision = 'ee5a1309c2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oracle_id', sa.String(length=120), nullable=True))
        batch_op.drop_column('scryfall_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scryfall_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('oracle_id')

    # ### end Alembic commands ###
