"""empty message

Revision ID: cbb575e75f94
Revises: 
Create Date: 2023-06-26 11:16:04.163897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb575e75f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('card_type', sa.String(length=120), nullable=False),
    sa.Column('mana_cost', sa.String(length=120), nullable=True),
    sa.Column('cmc', sa.Integer(), nullable=True),
    sa.Column('image_uri_small', sa.String(length=250), nullable=False),
    sa.Column('image_uri_normal', sa.String(length=250), nullable=False),
    sa.Column('is_restricted', sa.String(length=10), nullable=True),
    sa.Column('oracle_text', sa.String(length=750), nullable=True),
    sa.Column('flavor_text', sa.String(length=750), nullable=True),
    sa.Column('legalities', sa.String(length=250), nullable=True),
    sa.Column('artist', sa.String(length=120), nullable=False),
    sa.Column('scryfall_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scryfall_id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('format', sa.String(length=120), nullable=False),
    sa.Column('card_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_card_id', sa.Integer(), nullable=False),
    sa.Column('side_name', sa.String(length=120), nullable=False),
    sa.Column('side_card_type', sa.String(length=120), nullable=False),
    sa.Column('side_mana_cost', sa.String(length=120), nullable=True),
    sa.Column('side_cmc', sa.Integer(), nullable=True),
    sa.Column('side_image_uri_small', sa.String(length=250), nullable=False),
    sa.Column('side_image_uri_normal', sa.String(length=250), nullable=False),
    sa.Column('side_oracle_text', sa.String(length=750), nullable=True),
    sa.Column('side_flavor_text', sa.String(length=750), nullable=True),
    sa.ForeignKeyConstraint(['parent_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards_in_decks',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'deck_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_in_decks')
    op.drop_table('card_sides')
    op.drop_table('users')
    op.drop_table('decks')
    op.drop_table('cards')
    # ### end Alembic commands ###
