"""empty message

Revision ID: ef781a61f112
Revises: 
Create Date: 2023-06-07 13:29:31.237216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef781a61f112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('card_type', sa.String(length=120), nullable=False),
    sa.Column('mana_cost', sa.String(length=120), nullable=True),
    sa.Column('cmc', sa.Integer(), nullable=True),
    sa.Column('image_uri_small', sa.String(length=250), nullable=False),
    sa.Column('image_uri_normal', sa.String(length=250), nullable=False),
    sa.Column('oracle_text', sa.String(length=750), nullable=True),
    sa.Column('flavor_text', sa.String(length=750), nullable=True),
    sa.Column('legalities', sa.String(length=250), nullable=True),
    sa.Column('artist', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('format', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cards_in_decks',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_in_decks')
    op.drop_table('users')
    op.drop_table('decks')
    op.drop_table('cards')
    # ### end Alembic commands ###
